/- Reynolds operator:
  MvPolynomial.IsInvariant and Algebra.invariantSubalgebra

Noetherian ring:  IsNoetherian R M

Noetherian ring has explicit generators t1...tn:
Submodule.fg_iff_exists_fin_generating_family (or use submodule.fg_def)

The existence of finite generators:

finitely generated ideal:
Ideal.FG

finitely generated submodule:
Submodule.FG
-/

import Mathlib

variable (k G R : Type*)
  [Field k] -- field
  [Group G] -- group
  [CommRing R] --commutative ring
  [Algebra k R] -- R is a k-algebra
  [MulSemiringAction G R] -- G acts on R by algebra automorphisms
  [IsNoetherian R R] --Noetherian ring

-- The invariant subring R^G
def R_G := sorry

-- R^G_+ : irrelevant ideal, positive degree part
-- Needs graded structure to define properly
def R_G_plus : Ideal (R_G G R) := sorry

-- Main theorem:
-- prove R_G_plus is finitely generated
theorem R_G_plus_fg :
    (R_G_plus G R).FG := by
  -- Step 1: R is Noetherian so R^G_+·R is fg
  -- R^G_+·R is the ideal generated by R^G_+ in R, which is a submodule of R
  -- then check whether R^G_+·R is finitely generated
  have h1 : (R_G_plus G R • ⊤ : Submodule (R_G G R) R).FG := by
    exact IsNoetherian.noetherian _ --therefore every submodule is finitely generated
  -- h1 : ∃ s, s is finite ∧ s spans R^G_+·R where s = {f₁, f₂, ..., fₙ}
  rw [Submodule.fg_def] at h1
  obtain ⟨s, hs_fin, hs_span⟩ := h1
  -- Step 3: Reynolds argument
  have reynolds : ∀ f ∈ R_G_plus G R,
      ∃ c : R_G G R, f = sorry := by --c = rho (fi)
    sorry
  -- Step 4: Conclude
  exact sorry

#check IsNoetherian.noetherian
