import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.RingTheory.Ideal.Maps
import GIT.Invariants.GradedFiniteType

/-!
# Reynolds ideal machinery

Suppose `toR : A →ₐ[k] R` includes an invariant subalgebra `A = R^G ⊆ R` and `ρ : R →ₗ[k] A` is a
"Reynolds projection" (left inverse of `toR` and `A`-multiplicative on `toR a * r`). If a set
`s ⊆ R` ideal-spans the extension `extendedRGplus := R · (R^G)₊`, then the images `ρ '' s`
ideal-span `(R^G)₊` itself. This is the key tool for transferring f.g.-ness from `R` to `R^G`.

## Main definitions

* `GIT.ReynoldsGITSpanProperty` — `f ∈ Ideal.span s` pulls back through `ρ` to
  `f ∈ Ideal.span (ρ '' s)`.

## Main results

* `GIT.extendedRGplus_fg` — Noether: the extended ideal is f.g.
* `GIT.exists_generators_extendedRGplus_from_RGplus` — choose finitely many generators from the
  given spanning set.
* `GIT.RGplusA_fg_of_reynolds` — `(R^G)₊` is f.g. as an ideal of `R^G` under the Reynolds
  spanning property.
* `GIT.reynolds_rewrite`, `GIT.mem_ideal_span_lift_of_reynolds` — applying `ρ` to a relation.
* `GIT.exists_finset_presentation_of_mem_span` — write any element of `Ideal.span s` as a
  finite `s`-linear combination.
* `GIT.reynoldsGITSpanProperty_of_reynolds` — the abstract Reynolds projection witnesses
  `ReynoldsGITSpanProperty`.
-/

universe u

namespace GIT

/-- **Noether: the extended ideal is f.g.** -/
theorem extendedRGplus_fg
    {R : Type*} [CommRing R] [IsNoetherianRing R]
    (extendedRGplus : Ideal R) : extendedRGplus.FG :=
  IsNoetherian.noetherian extendedRGplus

/-- **F.g. submodule-span from f.g. ideal-span.** -/
private lemma fg_submodule_span_of_ideal_span
    {R : Type*} [CommRing R] {RGplusSet : Set R} {extendedRGplus : Ideal R}
    (hspan : Ideal.span RGplusSet = extendedRGplus)
    (hfg : extendedRGplus.FG) :
    (Submodule.span R RGplusSet : Submodule R R).FG := by
  have hfg_span_ideal : (Ideal.span RGplusSet).FG := by simpa [hspan] using hfg
  exact hfg_span_ideal

/-- **Pick finitely many generators of `extendedRGplus` from inside the spanning set.**

Math statement: if `Ideal.span RGplusSet = extendedRGplus` and `extendedRGplus` is f.g., then
there is a finset `s ⊆ RGplusSet` whose span is again `extendedRGplus`.

Proof idea: transfer the f.g. ideal-span to a f.g. submodule-span
(`fg_submodule_span_of_ideal_span`), then apply `Submodule.fg_span_iff_fg_span_finset_subset`. -/
theorem exists_generators_extendedRGplus_from_RGplus
    {R : Type*} [CommRing R] {RGplusSet : Set R} {extendedRGplus : Ideal R}
    (hspan : Ideal.span RGplusSet = extendedRGplus)
    (hfg : extendedRGplus.FG) :
    ∃ s : Finset R,
      (∀ x ∈ s, x ∈ RGplusSet) ∧
      Ideal.span (↑s : Set R) = extendedRGplus := by
  classical
  rcases (Submodule.fg_span_iff_fg_span_finset_subset (R := R) (M := R) RGplusSet).1
    (fg_submodule_span_of_ideal_span hspan hfg) with ⟨s, hs_sub, hs_span⟩
  refine ⟨s, hs_sub, ?_⟩
  calc Ideal.span (↑s : Set R) = Ideal.span RGplusSet := hs_span.symm
    _ = extendedRGplus := hspan

/-- **The Reynolds/GIT spanning property.** Spelled out: if `toR f` lies in the `R`-ideal
generated by `s`, then `f` lies in the `A`-ideal generated by the Reynolds images `ρ x` for
`x ∈ s`. -/
def ReynoldsGITSpanProperty
    {k : Type u} [Field k] {A : Type*} [CommRing A] [Algebra k A]
    {R : Type*} [CommRing R] [Algebra k R] [DecidableEq A]
    (toR : A →ₐ[k] R) (ρ : R →ₗ[k] A) (s : Finset R) : Prop :=
  ∀ f : A,
    toR f ∈ Ideal.span (↑s : Set R) →
      f ∈ Ideal.span ↑(Finset.image (fun x => ρ x) s)

variable {k : Type u} [Field k]
variable {A : Type*} [CommRing A] [Algebra k A] [DecidableEq A]
variable {R : Type*} [CommRing R] [Algebra k R]

/-- **Elements of `RGplusA` lie in the `A`-ideal generated by `ρ '' s`.** -/
theorem mem_span_of_reynolds_generators
    {toR : A →ₐ[k] R} {ρ : R →ₗ[k] A} {RGplusA : Ideal A} {extendedRGplus : Ideal R}
    {s : Finset R}
    (hs_span : Ideal.span (↑s : Set R) = extendedRGplus)
    (hcomap : RGplusA = Ideal.comap (toR : A →+* R) extendedRGplus)
    (hReynolds : ReynoldsGITSpanProperty toR ρ s)
    (f : A) (hf : f ∈ RGplusA) :
    f ∈ Ideal.span ↑(Finset.image (fun x => ρ x) s) := by
  refine hReynolds f ?_
  have hf_comap : f ∈ Ideal.comap (toR : A →+* R) extendedRGplus := by simpa [hcomap] using hf
  simpa [hs_span] using Ideal.mem_comap.mp hf_comap

/-- **`(R^G)₊` is f.g. as an ideal of `R^G`** under the Reynolds spanning property. Pair
`mem_span_of_reynolds_generators` (one direction of inclusion) with `Ideal.span_le`
(the other). -/
theorem RGplusA_fg_of_reynolds
    {toR : A →ₐ[k] R} {ρ : R →ₗ[k] A} {RGplusA : Ideal A} {extendedRGplus : Ideal R}
    {s : Finset R}
    (hs_span : Ideal.span (↑s : Set R) = extendedRGplus)
    (hcomap : RGplusA = Ideal.comap (toR : A →+* R) extendedRGplus)
    (hρ_gen : ∀ x ∈ s, ρ x ∈ RGplusA)
    (hReynolds : ReynoldsGITSpanProperty toR ρ s) :
    RGplusA.FG := by
  classical
  refine ⟨Finset.image (fun x => ρ x) s, le_antisymm ?_ ?_⟩
  · rw [Ideal.span_le]
    rintro y hy
    rcases Finset.mem_image.mp hy with ⟨x, hx, rfl⟩
    exact hρ_gen x hx
  · intro f hf
    exact mem_span_of_reynolds_generators hs_span hcomap hReynolds f hf

/-- **Apply `ρ` to a relation `toR f = Σ x · a x` to rewrite `f` as `Σ lift x · ρ (a x)`.** -/
theorem reynolds_rewrite (toR : A →ₐ[k] R) (ρ : R →ₗ[k] A) (s : Finset R) (lift : R → A)
    (f : A) (a_f : s → R)
    (hf : toR f = ∑ x ∈ s.attach, x.val * a_f x)
    (hlift : ∀ x ∈ s, toR (lift x) = x)
    (hρ_id : ∀ a : A, ρ (toR a) = a)
    (hρ_mul : ∀ (a : A) (r : R), ρ ((toR a) * r) = a * ρ r) :
    f = ∑ x ∈ s.attach, lift x.val * ρ (a_f x) := by
  have hρf : ρ (toR f) = ρ (∑ x ∈ s.attach, x.val * a_f x) := by rw [hf]
  rw [hρ_id, map_sum] at hρf
  rw [hρf]
  refine Finset.sum_congr rfl fun x _ => ?_
  have hmul := hρ_mul (lift x.val) (a_f x)
  rw [hlift x.val x.property] at hmul
  exact hmul

/-- **Ideal-membership form of `reynolds_rewrite`.** -/
theorem mem_ideal_span_lift_of_reynolds (toR : A →ₐ[k] R) (ρ : R →ₗ[k] A) (s : Finset R)
    (lift : R → A) (f : A) (coeff : s → R)
    (hf : toR f = ∑ x ∈ s.attach, x.val * coeff x)
    (hlift : ∀ x ∈ s, toR (lift x) = x)
    (hρ_id : ∀ a : A, ρ (toR a) = a)
    (hρ_mul : ∀ (a : A) (r : R), ρ ((toR a) * r) = a * ρ r) :
    f ∈ Ideal.span ((lift '' (s : Set R)) : Set A) := by
  rw [reynolds_rewrite toR ρ s lift f coeff hf hlift hρ_id hρ_mul]
  refine Ideal.sum_mem _ fun x _ => Ideal.mul_mem_right _ _ ?_
  exact Ideal.subset_span (Set.mem_image_of_mem lift x.property)

/-- **Single-generator case of `exists_finset_presentation_of_mem_span`:** any `y ∈ s` admits
the coefficient `[t ↦ if t = y then 1 else 0]`. -/
private lemma exists_finset_presentation_mem
    {R : Type*} [CommRing R] (s : Finset R) {y : R} (hy : y ∈ (s : Set R)) :
    ∃ coeff : s → R, y = ∑ t ∈ s.attach, t.val * coeff t := by
  classical
  refine ⟨fun t => if t.val = y then 1 else 0, ?_⟩
  rw [Finset.sum_eq_single (⟨y, by simpa using hy⟩ : {a // a ∈ s})]
  · simp
  · intro b _ hb_ne
    have hbval : b.val ≠ y := fun heq => hb_ne (Subtype.ext heq)
    simp [hbval]
  · intro h; exact (h (Finset.mem_attach _ _)).elim

/-- **Addition case of `exists_finset_presentation_of_mem_span`.** -/
private lemma exists_finset_presentation_add
    {R : Type*} [CommRing R] (s : Finset R) {ca cb : s → R} :
    ∃ cc : s → R, ∀ a b : R, a = ∑ t ∈ s.attach, t.val * ca t →
      b = ∑ t ∈ s.attach, t.val * cb t →
        a + b = ∑ t ∈ s.attach, t.val * cc t :=
  ⟨fun t => ca t + cb t, fun a b ha hb => by
    rw [ha, hb, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl ?_; intros; ring⟩

/-- **Scalar-multiplication case of `exists_finset_presentation_of_mem_span`.** -/
private lemma exists_finset_presentation_smul
    {R : Type*} [CommRing R] (s : Finset R) (r : R) {ca : s → R} :
    ∃ cc : s → R, ∀ a : R, a = ∑ t ∈ s.attach, t.val * ca t →
      r * a = ∑ t ∈ s.attach, t.val * cc t :=
  ⟨fun t => r * ca t, fun a ha => by
    rw [ha, Finset.mul_sum]
    refine Finset.sum_congr rfl ?_; intros; ring⟩

/-- **Extract a finite presentation from membership in `Ideal.span s`.**

Math statement: `x ∈ Ideal.span s ⟹ ∃ coeff : s → R, x = Σ t ∈ s.attach, t · coeff t`.

Proof idea: `Submodule.span_induction` on `x ∈ submodule-span s`, using the four case-helpers
`exists_finset_presentation_mem`, `_add`, `_smul`, and the trivial zero case. -/
lemma exists_finset_presentation_of_mem_span
    {R : Type*} [CommRing R] (s : Finset R) (x : R)
    (hx : x ∈ Ideal.span (↑s : Set R)) :
    ∃ coeff : s → R, x = ∑ t ∈ s.attach, t.val * coeff t := by
  classical
  refine Submodule.span_induction
    (p := fun y _ => ∃ coeff : s → R, y = ∑ t ∈ s.attach, t.val * coeff t)
    ?mem ?zero ?add ?smul (hx : x ∈ (Submodule.span R (↑s : Set R) : Submodule R R))
  case mem => intro y hy; exact exists_finset_presentation_mem s hy
  case zero => exact ⟨fun _ => 0, by simp⟩
  case add =>
    rintro a b _ _ ⟨ca, hca⟩ ⟨cb, hcb⟩
    obtain ⟨cc, hcc⟩ := exists_finset_presentation_add (ca := ca) (cb := cb) s
    exact ⟨cc, hcc a b hca hcb⟩
  case smul =>
    rintro r a _ ⟨ca, hca⟩
    obtain ⟨cc, hcc⟩ := exists_finset_presentation_smul (ca := ca) s r
    exact ⟨cc, by rw [smul_eq_mul]; exact hcc a hca⟩

/-- **On `s`, `ρ x = lift x`** since `lift x ∈ A` is fixed by `ρ ∘ toR`. -/
private lemma rho_eq_lift_on_s
    {toR : A →ₐ[k] R} {ρ : R →ₗ[k] A} {s : Finset R} {lift : R → A}
    (hlift : ∀ x ∈ s, toR (lift x) = x) (hρ_id : ∀ a : A, ρ (toR a) = a) :
    ∀ x ∈ s, ρ x = lift x := fun x hx =>
  (congrArg ρ (hlift x hx).symm).trans (hρ_id (lift x))

/-- **Set equality** `lift '' s = (Finset.image ρ s : Set A)` on the generating set. -/
private lemma lift_image_eq_rho_image
    {toR : A →ₐ[k] R} {ρ : R →ₗ[k] A} {s : Finset R} {lift : R → A}
    (hlift : ∀ x ∈ s, toR (lift x) = x) (hρ_id : ∀ a : A, ρ (toR a) = a) :
    (lift '' (s : Set R)) =
      ((Finset.image (fun x => ρ x) s : Finset A) : Set A) := by
  classical
  have hρ_eq_lift := rho_eq_lift_on_s hlift hρ_id
  ext a
  refine ⟨fun ⟨x, hxs, hax⟩ => ?_, fun ha => ?_⟩
  · exact Finset.mem_coe.mpr (Finset.mem_image.mpr ⟨x, hxs, (hρ_eq_lift x hxs).trans hax⟩)
  · rcases Finset.mem_image.mp (Finset.mem_coe.mp ha) with ⟨x, hxs, rfl⟩
    exact ⟨x, hxs, (hρ_eq_lift x hxs).symm⟩

/-- **The Reynolds projection witnesses `ReynoldsGITSpanProperty`.**

Math statement: under the standard Reynolds identities (left-inverse to `toR` and `A`-mul on
`toR a * r`), if `toR f ∈ Ideal.span s` then `f ∈ Ideal.span (ρ '' s)`.

Proof idea: extract a finite presentation of `toR f`
(`exists_finset_presentation_of_mem_span`); push `f` into `Ideal.span (lift '' s)` via
`mem_ideal_span_lift_of_reynolds`; rewrite `lift '' s = ρ '' s` on `s` (`lift_image_eq_rho_image`). -/
theorem reynoldsGITSpanProperty_of_reynolds
    (toR : A →ₐ[k] R) (ρ : R →ₗ[k] A) (s : Finset R) (lift : R → A)
    (hlift : ∀ x ∈ s, toR (lift x) = x)
    (hρ_id : ∀ a : A, ρ (toR a) = a)
    (hρ_mul : ∀ (a : A) (r : R), ρ ((toR a) * r) = a * ρ r) :
    ReynoldsGITSpanProperty toR ρ s := by
  classical
  intro f hf
  obtain ⟨coeff, hcoeff⟩ := exists_finset_presentation_of_mem_span s (toR f) hf
  have hf_lift := mem_ideal_span_lift_of_reynolds toR ρ s lift f coeff hcoeff hlift hρ_id hρ_mul
  rwa [lift_image_eq_rho_image hlift hρ_id] at hf_lift

end GIT
