import GIT.PRs.LinearlyReductive
import GIT.PRs.LocallyFinite

universe u

open Representation

variable {k : Type u} [Field k]
variable {G : Type u} [Group G]

/--
Existence of Reynolds operators for locally finite
representations of linearly reductive groups.

The proof proceeds by taking the finite-dimensional
G-stable subrepresentation generated by each vector
and applying the finite-dimensional Reynolds theorem.
-/
theorem exists_reynolds_of_locallyFinite
    (hlr : IsLinearlyReductive k G)
    (R : Type u)
    [AddCommGroup R]
    [Module k R]
    [DistribMulAction G R]
    [SMulCommClass G k R]
    (hlf : Representation.IsLocallyFinite k G R) :
    ∃ π : R →ₗ[k] R,
      True := by
  sorry
